apimServiceName: azure-apim-prod01

namedValues:

policies:

loggers:

diagnostics:

gateways:

backends:

versionSets:

groups:

subscriptions:

products:

apis:
  - name: sgw-test-api
    gateways:
      - name: "self-hosted-gateway-2"

tags:

policyFragments:

workspaces:
