apis:
  - ak-sgw-test-api01

backends:
  - ignore

gateways:

diagnostics:
  - ignore

groups:
  - ignore

loggers:
  - ignore

namedValues:
  - ignore

products:
  - ignore

subscriptions:
  - ignore

tags:
  - ignore

policyFragments:
  - ignore

versionSets:
  - ignore

workspaces:
  - ignore
